### ISSUE TITLE
use  jessie-backports to upgrade CMake 3.6

### ISSUE THREAD

**Issue by bc-lee** [Rikorose/gcc-cmake#1]
CMake 3.0 is not so recent package. Fortunately jessie-backports offer [CMake 3.6](https://packages.debian.org/jessie-backports/cmake). It will be awesome if this image supports CMake 3.6.

**Comment by Rikorose** [comment]
I am not familiar with the backports repo.

I guess the dockerfile should look like this:

```
FROM gcc:6

RUN deb http://ftp.debian.org/debian jessie-backports main \
  && apt-get update && apt-get -t jessie-backports install -y --no-install-recommends \
         cmake \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
```
